### ISSUE TITLE
Helm chart failing with nil pointer evaluating interface {}.repository

### ISSUE THREAD

**Issue by rishumehrotra** [MarquezProject/marquez-chart#1]
marquez-chart$ helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

marquez-chart$ helm install --generate-name .
Error: template: marquez/templates/deployment.yaml:24:28: executing "marquez/templates/deployment.yaml" at <.Values.image.repository>: nil pointer evaluating interface {}.repository

values.yaml

marquez:
  replicaCount: 1
  image:
    repository: marquez
    tag: 0.10.0
    pullPolicy: IfNotPresent
  db:

web:
  replicaCount: 1
  image:
    repository: marquez-web
    tag: 0.3.0
    pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "marquez.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "marquez.name" . }}
    helm.sh/chart: {{ include "marquez.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "marquez.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "marquez.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

**Comment by wslulciuc** [comment]
@rishumehrotra Thanks for opening this issue! (And for trying out the helm chart). Currently, the chart is WIP. I’m traveling, but will have time in a week or so to finish up my changes in the branch [feature/chart](https://github.com/MarquezProject/marquez-chart/tree/feature/chart)
